package classfile



const ACC_PUBLIC		  = 0x0001	// Declared public; may be accessed from outside its package.
const ACC_PRIVATE     = 0x0002  // Declared private; accessible only within thedefining class.
const ACC_PROTECTED   = 0x0004  // Declared protected; may be accessed within subclasses.
const ACC_STATIC      = 0x0008  // Declared static.
const ACC_FINAL		    = 0x0010	// Declared final; no subclasses allowed.
const ACC_SUPER		    = 0x0020	// Treat superclass methods specially when invoked by the invokespecial instruction.
const ACC_INTERFACE	  = 0x0200	// Is an interface, not a class.
const ACC_SYNCHRONIZED= 0x0020 // Declared synchronized; invocation is wrapped by a monitor use.
const ACC_BRIDGE      = 0x0040  // A bridge method, generated by the compiler.
const ACC_VARARGS     = 0x0080  // Declared with variable number of arguments.
const ACC_NATIVE      = 0x0100  // Declared native; implemented in a language other than the Java programming language.
const ACC_ABSTRACT	  = 0x0400	// Declared abstract; must not be instantiated.
const ACC_STRICT      = 0x0800  // Declared strictfp; floating-point mode is FP strict.
const ACC_SYNTHETIC	  = 0x1000	// Declared synthetic; not present in the source code.
const ACC_ANNOTATION	= 0x2000	// Declared as an annotation type.
const ACC_ENUM		    = 0x4000	// Declared as an enum type.
const ACC_MODULE		  = 0x8000	// Is a module, not a class or interface.

